spring:
  thymeleaf:
    prefix: classpath:/mail-templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        mime.charset: UTF-8
        transport:
          protocol: smtp


