spring:
  profiles:
    include: oauth
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc
  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
